### ISSUE TITLE
Chapter Idea: "Bad" File Formats

### ISSUE THREAD

**Issue by adelevie** [vdavez/codingforlawyers#4]
Why you should avoid creating:
- PDFs
- Word docs
- [your hated file format here]

**Comment by SyntaxColoring** [comment]
This is a good idea.  :+1:

It's definitely worth explaining what a Word document actually is.  The HTML chapter mentions copying something and saving it in "a plain text file," and I'll bet a lot of people mistakenly think that's what Word does.  An introduction to XML and file archives might be necessary as background for that.

**Comment by adelevie** [comment]
I think it's important for this book to state certain normative values, such as PDFs == bad. In that sense, we'd be moving away from pure tutorials to a bit more philosophy/opinion.

**Comment by vdavez** [comment]
This is a good idea. But, rather than describe them as bad file formats, I am planning on introducing CSV, JSON, HTML, and XML as "better" formats. Ultimately, for better or worse, none of the file formats other than Word or PDF are especially good for writing briefs (LaTex may be a tough sell).

But more importantly, I want lawyers to develop an intuition for DRY approaches to their work. If they realize, "Hey, I shouldn't need to copy and paste the caption every time I start a new document!", they will make smarter choices about their tools.

**Comment by tmcw** [comment]
> But, rather than describe them as bad file formats, I am planning on introducing CSV, JSON, HTML, and XML as "better" formats.

:+1: Took [the same approach w/ simple open data](http://simpleopendata.com/) and it's a good one.

There is some angle to @adelevie's point though that rings true: instead of just being file formats, people have feelings and expectations about files that go beyond the basics:
- There's a widespread perception that you can't edit / forge PDFs, which is entirely wrong
- Plenty of people use Microsoft Word _for_ track changes. Recommending Markdown in that case doesn't stick unless there's a successor to track changes (like... GitHub)

**Comment by adelevie** [comment]
I wrote a rough draft of a chapter on diffs and use Track Changes as an example: https://github.com/vzvenyach/codingforlawyers/pull/10

Tracking changes in a Word doc is better than not tracking changes in a Word doc, for sure. The Giant Git Chapter should cover the benefits of tracking changes with git and dvcs (and why that's better than passing around a word doc as an email attachment). Another point I make in the diff chapter is that diffs are usable for computers and not just people. It's how @konklone's FISA court scraper works (worked?), for example.

Also looks like we might need a chapter on DRY :dragon_face: :trumpet: :truck:

**Comment by vdavez** [comment]
Going to close and move to #23
