### ISSUE TITLE
Chapter Idea: Git and GitHub

### ISSUE THREAD

**Issue by adelevie** [vdavez/codingforlawyers#5]
Many lawyers are already on [GitHub](http://lawyersongithub.com)!

You can use your newly-acquired Markdown skills on GitHub.

GitHub is for documents.

You get diffs\* for free.

GitHub is for code.

It's really all just git and GitHub.
- I'm working on diff chapter.

**Comment by vdavez** [comment]
This is an essential chapter. I alluded to it here: http://codingforlawyers.com/chapters/ch4/#fn_2

The challenge is that I need to do more research on using the github clients, because the web interface is still very imperfect and the CLI is a bridge too far at the point where it makes sense to introduce git.

I also want to collect a few examples of law-related, non-code repositories where lawyers can gain comfort with the notion of VCS.

I also think that github is a big norms chapter. Want to make sure that I focus on the culture... That's a surprisingly large barrier for lawyers. Need to explain it right first.

**Comment by compleatang** [comment]
I'm of course biased, but an example repo perhaps of a plain text based contract negotiation could go a long way to showing the power of git and diffs. The text of the chapter could just walk through the repo step by step, diff by diff.

@adelevie you were definitely right a long time ago: year of the diff!

**Comment by adelevie** [comment]
GitHub (and not git) is also excellent for making everything annotatable. Comment on a line or an an entire commit. Also, this book should have a demo somewhere of `git blame` (or github dot com slash something slash blame).

**Comment by vdavez** [comment]
Going to integrate this into #23 Roadmap. It's clear that `git` is correct for the book. Just a matter of location.
